### ISSUE TITLE
Get rid of np.exp(...) to generate Bluestein Fourier Matrix

### ISSUE THREAD

**Issue by MichaelDoebereiner** [EMS-TU-Ilmenau/fastmat#45] opened 2018-11-07 11:40 UTC
I've determined that np.exp(...) might not have a good performance for large matrices. Maybe there's another way to create the Fourier Matrix in case of the Bluestein Fourier Transform.

**Comment by SebastianSemper** [comment] 2018-11-07 13:21
Which part of the fastmat code are you referring to? Since the only time
the np.exp(...) function is called in the Fourier class is during the
initialization of the class instance. This is only done once during
construction and as such not really a performance issue during the actual
execution of the transforms.

If this is not what you meant, you should be a little bit more specific. ;-)

**Comment by MichaelDoebereiner** [comment] 2018-11-07 14:08
You're right, I'm referring to this part. Since this is called only once at this part of the code, you can take it as an annotation in general. ;-)

**Comment by ChristophWWagner** [comment] 2018-11-07 14:42
I can confirm this is sort of performance-critical for larger orders. Assume you have an Fourier-based interpolator, this generation takes a couple of hundred ms for orders around ~1e6, which is not THAT large (but also not that small). I once observed bad performance when generating interpolator objects for varying data sizes but didn't attribute it to the exponential generation. If it is verified that that's the cause we should address it.

**Comment by MichaelDoebereiner** [comment] 2018-11-07 15:03
I made a short example, where you can see that there are faster solutions than np.exp(). Allthough I don't know exactly what this numexpr module does.
Even a straight forward solution with sine and cosine is faster than np.exp().

Example:

x = np.random.randn(1000000,1)*1j
%timeit np.exp(x)
70.4 ms ± 450 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit numexpr.evaluate('exp(x)')
16 ms ± 55 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
x = np.random.randn(1000000,1)
%timeit np.cos(x)+1j*np.sin(x)
46.6 ms ± 130 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

**Comment by ChristophWWagner** [comment] 2021-02-14 19:48
Modifications were resolved in d22813f0452cd732976662987f2a2aae5c046019 and introduced to `v0.2`.

**Closed by ChristophWWagner** 2021-02-14 19:48 UTC
Labels: performance, polishing
